# Simple Frontend Pipeline for Tournament App
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - frontend/*
    - Dockerfile
    - azure-pipelines-frontend.yml

variables:
  # Docker variables
  dockerHubConnection: 'docker-hub-connection'
  frontendRepository: 'neepurna/tournament-frontend'
  dockerTag: '$(Build.BuildId)'
  
  # Kubernetes variables
  k8sNamespace: 'tournament-app'
  deploymentName: 'tournament-frontend'

stages:
- stage: Build
  displayName: 'Build and Push Frontend'
  jobs:
  - job: BuildFrontend
    displayName: 'Build Frontend Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - task: UseNode@1
      displayName: 'Use Node.js 18'
      inputs:
        version: '18.x'
    
    - script: |
        echo "Installing dependencies..."
        cd frontend
        npm install
        npm run build
        ls -la build/
      displayName: 'Build Frontend Application'
      continueOnError: false
    
    - task: Docker@2
      displayName: 'Build and Push Frontend Docker Image'
      inputs:
        containerRegistry: '$(dockerHubConnection)'
        repository: '$(frontendRepository)'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        buildContext: '.'
        tags: |
          $(dockerTag)
          latest
    
    - script: |
        echo "=========================================="
        echo "🚀 BUILD COMPLETE!"
        echo "=========================================="
        echo "Frontend Image: $(frontendRepository):$(dockerTag)"
        echo "Frontend Image: $(frontendRepository):latest"
        echo "=========================================="
      displayName: 'Build Summary'

- stage: Deploy
  displayName: 'Deploy to Kubernetes'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployToK8s
    displayName: 'Deploy to Kubernetes'
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - script: |
        echo "Deployment step - Manual kubectl commands needed"
        echo "=========================================="
        echo "To deploy manually, run these commands:"
        echo "=========================================="
        echo "kubectl set image deployment/$(deploymentName) tournament-frontend=$(frontendRepository):$(dockerTag) -n $(k8sNamespace)"
        echo "kubectl rollout status deployment/$(deploymentName) -n $(k8sNamespace)"
        echo "kubectl get pods -n $(k8sNamespace)"
        echo "=========================================="
      displayName: 'Deployment Instructions'
