apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-royale-redis
  namespace: quiz-royale
  labels:
    app: quiz-royale-redis
    tier: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-royale-redis
  template:
    metadata:
      labels:
        app: quiz-royale-redis
        tier: cache
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "6379"
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: quiz-royale-secrets
              key: REDIS_PASSWORD
        command:
        - redis-server
        - --requirepass
        - $(REDIS_PASSWORD)
        - --maxmemory
        - 256mb
        - --maxmemory-policy
        - allkeys-lru
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-tmp
          mountPath: /tmp
      volumes:
      - name: redis-data
        emptyDir: {}
      - name: redis-tmp
        emptyDir: {}
      securityContext:
        fsGroup: 999
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-royale-redis
  namespace: quiz-royale
  labels:
    app: quiz-royale-redis
spec:
  selector:
    app: quiz-royale-redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  type: ClusterIP
