apiVersion: v1
kind: Secret
metadata:
  name: quiz-royale-secrets
  namespace: quiz-royale
type: Opaque
stringData:
  # These will be populated by the deployment script
  DATABASE_URL: "postgresql://quiz_royale_user:PASSWORD@DB_HOST:5432/quiz_royale"
  JWT_SECRET: "your-jwt-secret-here"
  REDIS_URL: "redis://REDIS_HOST:6379"
  REDIS_PASSWORD: "your-redis-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: quiz-royale-monitoring
type: Opaque
stringData:
  admin-password: "admin123"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-royale-config
  namespace: quiz-royale
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  MAX_TOURNAMENT_PLAYERS: "100"
  TOURNAMENT_DURATION: "300"
  QUESTION_TIME_LIMIT: "30"
  WEBSOCKET_ENABLED: "true"
  RATE_LIMIT_WINDOW: "900"
  RATE_LIMIT_MAX: "100"
