name: Smart Contracts CI

on:
  push:
    branches: [ main ]
    paths:
      - 'contracts/**'
      - 'hardhat.config.ts'
      - 'test/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'contracts/**'
      - 'hardhat.config.ts'
      - 'test/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Compile contracts
        run: npx hardhat compile
      
      - name: Run tests
        run: npx hardhat test
      
      - name: Run coverage
        run: npx hardhat coverage || echo "No coverage configured"
