name: Docker Publish

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'

env:
  ACR_NAME: quizroyaleacr
  AZURE_RESOURCE_GROUP: quiz-royale-rg

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push Docker images
      run: |
        ACR_LOGIN_SERVER=$(az acr show --name ${{ env.ACR_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --query loginServer --output tsv)
        
        az acr login --name ${{ env.ACR_NAME }}
        
        cd frontend
        docker build -t $ACR_LOGIN_SERVER/quiz-royale-frontend:${{ github.sha }} .
        docker push $ACR_LOGIN_SERVER/quiz-royale-frontend:${{ github.sha }}
